### PR TITLE
Fix some security issues

### PR DESCRIPTION
**Pull request by ir-3**
Player Info:
- [X] Disallowed command chaining
- [X] Checked if the length was valid
- [X] Throws an error if there were invalid characters inside of the username

Nation Info:
- [X] Disallowed command chaining
- [ ] Checked if the length was valid
- [ ] Throws an error if there were invalid characters inside of the nation-name.

Settlement Info:
- [X] Disallowed command chaining
- [ ] Checked if the length was valid
- [ ] Throws an error if there were invalid characters inside of the settlement-name.

The check-boxes that are missing require the following information for me to fix.
- How long a nation-name can be
- How long a settlement-name can be
- What characters are allowed inside of a nation-name
- What characters are allowed inside of a settlement-name

Hope this helps!

### CODE REVIEW

**Comment by Peter-Crawley** [comment]
Settlements and Nations have the same requirements in terms of name
3 to 40 chars and must only use A-Z a-z and 0-9

**Comment by ir-3** [comment]
Are underscores allowed?

**Comment by Peter-Crawley** [comment]
no

**Comment by Peter-Crawley** [comment]
no

**Comment by Peter-Crawley** [comment]
Issue resolved in 2.0 rewrite.

**Pull request closed without merging**
